/**
 * Mock data for the ReSello consumer demo.
 *
 * In production this data comes from the ReSello POS: the till knows which item
 * sits on which table at which flea market, which is exactly what makes the
 * consumer search possible. Here it is a static, hand written stand in.
 *
 * Markets marked `plausible: true` are invented for the demo; the others are
 * modelled on real Finnish self service flea markets (addresses approximate).
 */

import { LatLng } from './geo';

export type Weekday = 'ma' | 'ti' | 'ke' | 'to' | 'pe' | 'la' | 'su';

export const WEEKDAYS: Weekday[] = ['ma', 'ti', 'ke', 'to', 'pe', 'la', 'su'];

export interface OpeningHour {
  open: string;
  close: string;
}

export type Category =
  | 'Vaatteet'
  | 'Lastentarvikkeet'
  | 'Astiat'
  | 'Sisustus'
  | 'Vintage'
  | 'Jalkineet'
  | 'Urheilu'
  | 'Kirjat';

export type Condition = 'Uudenveroinen' | 'Hyvä' | 'Käytetty';

export type ProductStatus = 'available' | 'reserved' | 'sold';

export type StyleTag =
  | 'skandi'
  | 'vintage'
  | 'maanläheinen'
  | 'minimalistinen'
  | 'retro'
  | 'värikäs'
  | 'klassinen';

export interface Market extends LatLng {
  id: string;
  name: string;
  city: string;
  district: string;
  address: string;
  postalCode: string;
  rating: number;
  reviewCount: number;
  tableCount: number;
  photo: string;
  hours: Record<Weekday, OpeningHour | null>;
  tags: string[];
  description: string;
  plausible?: boolean;
}

export interface Product {
  id: string;
  title: string;
  brand?: string;
  category: Category;
  size?: string;
  sizeGroup: 'kids' | 'adult' | 'shoes' | 'none';
  condition: Condition;
  price: number;
  marketId: string;
  spot: string;
  addedDaysAgo: number;
  photos: string[];
  color: string;
  style: StyleTag[];
  status: ProductStatus;
  sustainabilityNote: string;
  keywords: string[];
}

const hours = (
  weekday: [string, string],
  saturday: [string, string] | null,
  sunday: [string, string] | null,
): Record<Weekday, OpeningHour | null> => ({
  ma: { open: weekday[0], close: weekday[1] },
  ti: { open: weekday[0], close: weekday[1] },
  ke: { open: weekday[0], close: weekday[1] },
  to: { open: weekday[0], close: weekday[1] },
  pe: { open: weekday[0], close: weekday[1] },
  la: saturday ? { open: saturday[0], close: saturday[1] } : null,
  su: sunday ? { open: sunday[0], close: sunday[1] } : null,
});

export const markets: Market[] = [
  {
    id: 'm-ogeli',
    name: 'Ogelin kirppis',
    city: 'Helsinki',
    district: 'Oulunkylä',
    address: 'Kylänvanhimmantie 29',
    postalCode: '00640',
    lat: 60.228,
    lng: 24.97,
    rating: 4.6,
    reviewCount: 412,
    tableCount: 180,
    photo: 'market-ogeli',
    hours: hours(['10.00', '19.00'], ['10.00', '17.00'], ['12.00', '17.00']),
    tags: ['Lastentarvikkeet', 'Vaatteet', 'Astiat'],
    description:
      'Iso itsepalvelukirppis Oulunkylässä. Laaja lastenosasto ja vaihtuva valikoima kausivaatteita.',
  },
  {
    id: 'm-kanuuna',
    name: 'Kaivarin Kanuuna',
    city: 'Helsinki',
    district: 'Ullanlinna',
    address: 'Neitsytpolku 4',
    postalCode: '00140',
    lat: 60.158,
    lng: 24.952,
    rating: 4.4,
    reviewCount: 238,
    tableCount: 90,
    photo: 'market-kanuuna',
    hours: hours(['11.00', '18.00'], ['11.00', '16.00'], null),
    tags: ['Vaatteet', 'Vintage', 'Design'],
    description:
      'Pieni ja tarkkaan kuratoitu kirppis meren läheisyydessä. Paljon merkkivaatteita ja designlöytöjä.',
  },
  {
    id: 'm-hertsika',
    name: 'Hertsikan Kirppis',
    city: 'Helsinki',
    district: 'Herttoniemi',
    address: 'Linnanrakentajantie 2',
    postalCode: '00880',
    lat: 60.193,
    lng: 25.033,
    rating: 4.3,
    reviewCount: 315,
    tableCount: 140,
    photo: 'market-hertsika',
    hours: hours(['10.00', '19.00'], ['10.00', '18.00'], ['11.00', '17.00']),
    tags: ['Vaatteet', 'Lastentarvikkeet', 'Sisustus'],
    description: 'Metron vieressä, helppo pysäköidä. Vahva vaate ja sisustusvalikoima.',
  },
  {
    id: 'm-vekara',
    name: 'Vekarakirppis',
    city: 'Helsinki',
    district: 'Konala',
    address: 'Ruosilantie 14',
    postalCode: '00390',
    lat: 60.238,
    lng: 24.856,
    rating: 4.7,
    reviewCount: 521,
    tableCount: 210,
    photo: 'market-vekara',
    hours: hours(['10.00', '18.00'], ['10.00', '16.00'], ['12.00', '16.00']),
    tags: ['Lastentarvikkeet', 'Lelut', 'Vaunut'],
    description:
      'Erikoistunut lastentarvikkeisiin. Haalarit, rattaat ja turvaistuimet omilla osastoillaan.',
  },
  {
    id: 'm-dom',
    name: 'DoM Itsepalvelukirpputori',
    city: 'Helsinki',
    district: 'Malmi',
    address: 'Malminkaari 5',
    postalCode: '00700',
    lat: 60.25,
    lng: 25.01,
    rating: 4.2,
    reviewCount: 189,
    tableCount: 160,
    photo: 'market-dom',
    hours: hours(['10.00', '20.00'], ['10.00', '18.00'], ['12.00', '18.00']),
    tags: ['Vaatteet', 'Lastentarvikkeet', 'Huonekalut'],
    description: 'Pitkät aukioloajat ja iso pöytämäärä. Hyvä paikka nopealle kierrokselle.',
  },
  {
    id: 'm-zirppari',
    name: 'Zirppari',
    city: 'Helsinki',
    district: 'Pitäjänmäki',
    address: 'Takkatie 18',
    postalCode: '00370',
    lat: 60.222,
    lng: 24.86,
    rating: 4.1,
    reviewCount: 143,
    tableCount: 120,
    photo: 'market-zirppari',
    hours: hours(['11.00', '19.00'], ['10.00', '17.00'], null),
    tags: ['Vaatteet', 'Vintage', 'Urheilu'],
    description: 'Teollisuusalueen kirppis, jossa on paljon vaatepuomeja ja vintagea.',
  },
  {
    id: 'm-hiiden',
    name: 'Hiiden Kirppis',
    city: 'Vihti',
    district: 'Nummela',
    address: 'Pisteenkaari 3',
    postalCode: '03100',
    lat: 60.334,
    lng: 24.329,
    rating: 4.5,
    reviewCount: 276,
    tableCount: 250,
    photo: 'market-hiiden',
    hours: hours(['10.00', '18.00'], ['10.00', '16.00'], ['11.00', '16.00']),
    tags: ['Huonekalut', 'Vintage', 'Astiat'],
    description: 'Suuri halli, jossa on runsaasti huonekaluja ja vanhaa tavaraa.',
  },
  {
    id: 'm-nurkka',
    name: 'Nurkka Second Hand',
    city: 'Turku',
    district: 'Kupittaa',
    address: 'Lemminkäisenkatu 30',
    postalCode: '20520',
    lat: 60.447,
    lng: 22.29,
    rating: 4.6,
    reviewCount: 198,
    tableCount: 110,
    photo: 'market-nurkka',
    hours: hours(['11.00', '18.00'], ['11.00', '16.00'], null),
    tags: ['Vaatteet', 'Vintage', 'Sisustus'],
    description: 'Kuratoitu second hand piste opiskelijakaupungin ytimessä.',
  },
  {
    id: 'm-keidas',
    name: 'Kirppis-Keidas',
    city: 'Salo',
    district: 'Keskusta',
    address: 'Örninkatu 15',
    postalCode: '24100',
    lat: 60.386,
    lng: 23.132,
    rating: 4.3,
    reviewCount: 96,
    tableCount: 130,
    photo: 'market-keidas',
    hours: hours(['10.00', '18.00'], ['10.00', '15.00'], null),
    tags: ['Vaatteet', 'Astiat', 'Jalkineet'],
    description: 'Rauhallinen kirppis keskustassa, kahvila samassa tilassa.',
  },
  {
    id: 'm-lykky',
    name: 'Lykky Kirppis & Kahvila',
    city: 'Rauma',
    district: 'Keskusta',
    address: 'Nortamonkatu 7',
    postalCode: '26100',
    lat: 61.129,
    lng: 21.512,
    rating: 4.8,
    reviewCount: 154,
    tableCount: 85,
    photo: 'market-lykky',
    hours: hours(['10.00', '17.00'], ['10.00', '15.00'], null),
    tags: ['Vaatteet', 'Sisustus', 'Kahvila'],
    description: 'Kirppis ja kahvila saman katon alla, kiireetön tunnelma.',
  },
  {
    id: 'm-koto',
    name: 'Koto Kirpputori',
    city: 'Oulu',
    district: 'Keskusta',
    address: 'Isokatu 47',
    postalCode: '90100',
    lat: 65.0135,
    lng: 25.472,
    rating: 4.5,
    reviewCount: 221,
    tableCount: 150,
    photo: 'market-koto',
    hours: hours(['10.00', '18.00'], ['10.00', '16.00'], ['12.00', '16.00']),
    tags: ['Lastentarvikkeet', 'Vaatteet', 'Juhlavaatteet'],
    description:
      'Keskustan kirppis kävelymatkan päässä hotelleista. Lasten juhlavaatteet omassa nurkassaan.',
  },
  {
    id: 'm-oulu-iso',
    name: 'Oulun Iso Kirppis',
    city: 'Oulu',
    district: 'Limingantulli',
    address: 'Nuottasaarentie 5',
    postalCode: '90400',
    lat: 65.0,
    lng: 25.48,
    rating: 4.2,
    reviewCount: 187,
    tableCount: 300,
    photo: 'market-oulu-iso',
    hours: hours(['10.00', '19.00'], ['10.00', '17.00'], ['12.00', '17.00']),
    tags: ['Vaatteet', 'Lastentarvikkeet', 'Sisustus'],
    description: 'Oulun suurin pöytämäärä ja pitkät aukioloajat.',
    plausible: true,
  },
  {
    id: 'm-akirppis',
    name: 'A-Kirppis Haukipudas',
    city: 'Oulu',
    district: 'Haukipudas',
    address: 'Revontie 2',
    postalCode: '90830',
    lat: 65.178,
    lng: 25.35,
    rating: 4.4,
    reviewCount: 88,
    tableCount: 95,
    photo: 'market-akirppis',
    hours: hours(['10.00', '17.00'], ['10.00', '15.00'], null),
    tags: ['Lastentarvikkeet', 'Vaatteet', 'Käsityöt'],
    description: 'Kylän oma kirppis, jossa on paljon lasten ulkovaatteita ja käsitöitä.',
  },
  {
    id: 'm-lanttila',
    name: 'Perhekirppis Lanttila',
    city: 'Lahti',
    district: 'Keskusta',
    address: 'Vesijärvenkatu 25',
    postalCode: '15140',
    lat: 60.984,
    lng: 25.656,
    rating: 4.7,
    reviewCount: 304,
    tableCount: 220,
    photo: 'market-lanttila',
    hours: hours(['10.00', '19.00'], ['10.00', '17.00'], ['12.00', '17.00']),
    tags: ['Astiat', 'Sisustus', 'Lastentarvikkeet'],
    description:
      'Lahden laajin astiavalikoima. Omat vitriinit designastioille ja kokonaiset astiastot hyllyissä.',
  },
  {
    id: 'm-hyrra',
    name: 'Kirppis Hyrrä',
    city: 'Lahti',
    district: 'Keskusta',
    address: 'Aleksanterinkatu 18',
    postalCode: '15110',
    lat: 60.98,
    lng: 25.662,
    rating: 4.3,
    reviewCount: 142,
    tableCount: 120,
    photo: 'market-hyrra',
    hours: hours(['11.00', '18.00'], ['10.00', '16.00'], null),
    tags: ['Astiat', 'Vaatteet', 'Kirjat'],
    description: 'Keskustan kirppis, jossa kahvikupit ja lasit ovat omalla osastollaan.',
    plausible: true,
  },
  {
    id: 'm-tammela',
    name: 'Tammelan Aarrekirppis',
    city: 'Tampere',
    district: 'Tammela',
    address: 'Itsenäisyydenkatu 12',
    postalCode: '33500',
    lat: 61.499,
    lng: 23.776,
    rating: 4.4,
    reviewCount: 167,
    tableCount: 170,
    photo: 'market-tammela',
    hours: hours(['10.00', '18.00'], ['10.00', '16.00'], ['12.00', '16.00']),
    tags: ['Vaatteet', 'Lastentarvikkeet', 'Urheilu'],
    description: 'Aseman kupeessa, helppo poiketa junamatkalla.',
    plausible: true,
  },
  {
    id: 'm-kangas',
    name: 'Kankaan Kirppis',
    city: 'Jyväskylä',
    district: 'Kangas',
    address: 'Kangaskatu 3',
    postalCode: '40100',
    lat: 62.248,
    lng: 25.736,
    rating: 4.5,
    reviewCount: 129,
    tableCount: 140,
    photo: 'market-kangas',
    hours: hours(['11.00', '18.00'], ['10.00', '16.00'], null),
    tags: ['Vintage', 'Kirjat', 'Sisustus'],
    description: 'Vanhaan tehdaskiinteistöön rakennettu kirppis, vahva vintagevalikoima.',
    plausible: true,
  },
];

interface ProductInput extends Omit<Product, 'photos' | 'status' | 'sustainabilityNote' | 'keywords'> {
  status?: ProductStatus;
  sustainabilityNote?: string;
  keywords?: string[];
}

const NOTES: Record<Category, string> = {
  Vaatteet: 'Käytetty vaate säästää noin 10 kg hiilidioksidipäästöjä uuteen verrattuna.',
  Lastentarvikkeet: 'Lasten vaate ehtii palvella montaa perhettä, ennen kuin se on loppuun käytetty.',
  Astiat: 'Astiat kestävät sukupolvia, second hand on niille luonnollisin kierto.',
  Sisustus: 'Sisustustavara saa uuden kodin sen sijaan, että se päätyisi varastoon.',
  Vintage: 'Vintagelöytö on kierrätystä ja tyylivalinta samassa.',
  Jalkineet: 'Hyväkuntoiset kengät ansaitsevat toisen kierroksen.',
  Urheilu: 'Urheiluvälineet seisovat usein käyttämättöminä, kierrätys pitää ne liikkeessä.',
  Kirjat: 'Kirja on valmis luettavaksi uudelleen, sellaisenaan.',
};

function product(input: ProductInput): Product {
  return {
    ...input,
    status: input.status ?? 'available',
    sustainabilityNote: input.sustainabilityNote ?? NOTES[input.category],
    keywords: input.keywords ?? [],
    photos: [1, 2, 3].map((n) =>
      n === 1 ? `product-photos/${input.id}` : `product-photos/${input.id}-${n}`,
    ),
  };
}

export const products: Product[] = [
  /* -------- Helsinki, lasten haalarit (skriptattu kysely 1) -------- */
  product({
    id: 'p-001',
    title: 'Reima Tec talvihaalari',
    brand: 'Reima',
    category: 'Lastentarvikkeet',
    size: '122',
    sizeGroup: 'kids',
    condition: 'Hyvä',
    price: 35,
    marketId: 'm-ogeli',
    spot: 'Pöytä 12',
    addedDaysAgo: 0,
    color: 'Tummansininen',
    style: ['skandi', 'minimalistinen'],
    keywords: ['haalari', 'talvihaalari', 'ulkovaatteet', 'lapsi'],
  }),
  product({
    id: 'p-002',
    title: 'Lindex kevythaalari',
    brand: 'Lindex',
    category: 'Lastentarvikkeet',
    size: '122',
    sizeGroup: 'kids',
    condition: 'Uudenveroinen',
    price: 18,
    marketId: 'm-ogeli',
    spot: 'Hylly A3',
    addedDaysAgo: 0,
    color: 'Vaaleanvihreä',
    style: ['skandi', 'maanläheinen'],
    keywords: ['haalari', 'kevythaalari', 'välikausi', 'lapsi'],
  }),
  product({
    id: 'p-003',
    title: 'Didriksons sadehaalari',
    brand: 'Didriksons',
    category: 'Lastentarvikkeet',
    size: '122',
    sizeGroup: 'kids',
    condition: 'Hyvä',
    price: 24,
    marketId: 'm-dom',
    spot: 'Pöytä 7',
    addedDaysAgo: 1,
    color: 'Keltainen',
    style: ['värikäs'],
    keywords: ['haalari', 'sadehaalari', 'lapsi'],
  }),
  product({
    id: 'p-004',
    title: 'Polarn O. Pyret välikausihaalari',
    brand: 'Polarn O. Pyret',
    category: 'Lastentarvikkeet',
    size: '122',
    sizeGroup: 'kids',
    condition: 'Hyvä',
    price: 28,
    marketId: 'm-hertsika',
    spot: 'Pöytä 21',
    addedDaysAgo: 2,
    color: 'Harmaa',
    style: ['skandi', 'minimalistinen'],
    keywords: ['haalari', 'välikausihaalari', 'lapsi'],
  }),
  product({
    id: 'p-005',
    title: 'Reima toppahaalari',
    brand: 'Reima',
    category: 'Lastentarvikkeet',
    size: '128',
    sizeGroup: 'kids',
    condition: 'Käytetty',
    price: 15,
    marketId: 'm-vekara',
    spot: 'Pöytä 4',
    addedDaysAgo: 3,
    color: 'Punainen',
    style: ['värikäs'],
    keywords: ['haalari', 'toppahaalari', 'lapsi'],
  }),
  product({
    id: 'p-006',
    title: 'H&M fleecehaalari',
    brand: 'H&M',
    category: 'Lastentarvikkeet',
    size: '116',
    sizeGroup: 'kids',
    condition: 'Hyvä',
    price: 12,
    marketId: 'm-ogeli',
    spot: 'Pöytä 12',
    addedDaysAgo: 1,
    color: 'Beige',
    style: ['maanläheinen'],
    keywords: ['haalari', 'fleece', 'lapsi'],
  }),
  product({
    id: 'p-007',
    title: 'Reima kurahaalari',
    brand: 'Reima',
    category: 'Lastentarvikkeet',
    size: '122',
    sizeGroup: 'kids',
    condition: 'Hyvä',
    price: 20,
    marketId: 'm-vekara',
    spot: 'Pöytä 18',
    addedDaysAgo: 0,
    color: 'Vihreä',
    style: ['maanläheinen'],
    keywords: ['haalari', 'kurahaalari', 'lapsi'],
  }),

  /* -------- Helsinki, Levi's farkut (skriptattu kysely 2) -------- */
  product({
    id: 'p-010',
    title: "Levi's 501 farkut",
    brand: "Levi's",
    category: 'Vaatteet',
    size: 'M (W31)',
    sizeGroup: 'adult',
    condition: 'Hyvä',
    price: 29,
    marketId: 'm-kanuuna',
    spot: 'Pöytä 3',
    addedDaysAgo: 0,
    color: 'Sininen',
    style: ['klassinen', 'vintage'],
    keywords: ['farkut', 'jeans', 'denim'],
  }),
  product({
    id: 'p-011',
    title: "Levi's 511 slim farkut",
    brand: "Levi's",
    category: 'Vaatteet',
    size: 'S (W29)',
    sizeGroup: 'adult',
    condition: 'Uudenveroinen',
    price: 34,
    marketId: 'm-ogeli',
    spot: 'Pöytä 8',
    addedDaysAgo: 0,
    color: 'Tumma indigo',
    style: ['minimalistinen', 'klassinen'],
    keywords: ['farkut', 'jeans', 'slim', 'denim'],
  }),
  product({
    id: 'p-012',
    title: "Levi's 721 korkeavyötäröiset farkut",
    brand: "Levi's",
    category: 'Vaatteet',
    size: 'S (W28)',
    sizeGroup: 'adult',
    condition: 'Hyvä',
    price: 27,
    marketId: 'm-zirppari',
    spot: 'Hylly B2',
    addedDaysAgo: 1,
    color: 'Vaaleansininen',
    style: ['vintage', 'klassinen'],
    keywords: ['farkut', 'jeans', 'high waist', 'denim'],
  }),
  product({
    id: 'p-013',
    title: "Levi's farkkutakki",
    brand: "Levi's",
    category: 'Vaatteet',
    size: 'M',
    sizeGroup: 'adult',
    condition: 'Hyvä',
    price: 39,
    marketId: 'm-hertsika',
    spot: 'Pöytä 14',
    addedDaysAgo: 2,
    color: 'Sininen',
    style: ['vintage', 'klassinen'],
    status: 'reserved',
    keywords: ['farkkutakki', 'denim', 'takki'],
  }),
  product({
    id: 'p-014',
    title: "Levi's 550 farkut",
    brand: "Levi's",
    category: 'Vaatteet',
    size: 'M (W32)',
    sizeGroup: 'adult',
    condition: 'Käytetty',
    price: 15,
    marketId: 'm-dom',
    spot: 'Pöytä 9',
    addedDaysAgo: 4,
    color: 'Haalistunut sininen',
    style: ['vintage', 'retro'],
    keywords: ['farkut', 'jeans', 'denim'],
  }),

  /* -------- Oulu, lasten juhlamekot (skriptattu kysely 3) -------- */
  product({
    id: 'p-020',
    title: 'Marimekko lasten mekko',
    brand: 'Marimekko',
    category: 'Lastentarvikkeet',
    size: '110',
    sizeGroup: 'kids',
    condition: 'Hyvä',
    price: 26,
    marketId: 'm-koto',
    spot: 'Pöytä 5',
    addedDaysAgo: 0,
    color: 'Valkoinen ja punainen',
    style: ['skandi', 'värikäs'],
    keywords: ['mekko', 'juhlamekko', 'lapsi'],
  }),
  product({
    id: 'p-021',
    title: 'Lindex juhlamekko tyllihelmalla',
    brand: 'Lindex',
    category: 'Lastentarvikkeet',
    size: '110',
    sizeGroup: 'kids',
    condition: 'Uudenveroinen',
    price: 19,
    marketId: 'm-koto',
    spot: 'Hylly C1',
    addedDaysAgo: 1,
    color: 'Puuteripunainen',
    style: ['klassinen'],
    keywords: ['mekko', 'juhlamekko', 'tylli', 'lapsi'],
  }),
  product({
    id: 'p-022',
    title: 'Kanz kukkamekko',
    brand: 'Kanz',
    category: 'Lastentarvikkeet',
    size: '110',
    sizeGroup: 'kids',
    condition: 'Hyvä',
    price: 14,
    marketId: 'm-oulu-iso',
    spot: 'Pöytä 18',
    addedDaysAgo: 1,
    color: 'Sinikukallinen',
    style: ['värikäs'],
    keywords: ['mekko', 'kukkamekko', 'lapsi'],
  }),
  product({
    id: 'p-023',
    title: 'Reima trikoomekko',
    brand: 'Reima',
    category: 'Lastentarvikkeet',
    size: '116',
    sizeGroup: 'kids',
    condition: 'Hyvä',
    price: 12,
    marketId: 'm-akirppis',
    spot: 'Pöytä 2',
    addedDaysAgo: 3,
    color: 'Turkoosi',
    style: ['skandi'],
    keywords: ['mekko', 'lapsi'],
  }),
  product({
    id: 'p-024',
    title: 'Name It samettimekko',
    brand: 'Name It',
    category: 'Lastentarvikkeet',
    size: '110',
    sizeGroup: 'kids',
    condition: 'Uudenveroinen',
    price: 17,
    marketId: 'm-oulu-iso',
    spot: 'Pöytä 6',
    addedDaysAgo: 0,
    color: 'Tummanvihreä',
    style: ['klassinen', 'maanläheinen'],
    keywords: ['mekko', 'juhlamekko', 'sametti', 'lapsi'],
  }),
  product({
    id: 'p-025',
    title: 'Lasten juhlakengät',
    brand: 'Pom Pom',
    category: 'Jalkineet',
    size: '28',
    sizeGroup: 'shoes',
    condition: 'Hyvä',
    price: 15,
    marketId: 'm-koto',
    spot: 'Hylly C2',
    addedDaysAgo: 2,
    color: 'Musta',
    style: ['klassinen'],
    keywords: ['kengät', 'juhlakengät', 'lapsi'],
  }),

  /* -------- Lahti, astiat (skriptattu kysely 4) -------- */
  product({
    id: 'p-030',
    title: 'Iittala Teema lautaset 4 kpl',
    brand: 'Iittala',
    category: 'Astiat',
    sizeGroup: 'none',
    condition: 'Uudenveroinen',
    price: 45,
    marketId: 'm-lanttila',
    spot: 'Hylly D2',
    addedDaysAgo: 0,
    color: 'Valkoinen',
    style: ['skandi', 'minimalistinen'],
    keywords: ['lautaset', 'astiat', 'astiasto', 'keittiö'],
  }),
  product({
    id: 'p-031',
    title: 'Arabia Paratiisi vati',
    brand: 'Arabia',
    category: 'Astiat',
    sizeGroup: 'none',
    condition: 'Hyvä',
    price: 60,
    marketId: 'm-lanttila',
    spot: 'Vitriini 1',
    addedDaysAgo: 1,
    color: 'Sinivalkoinen',
    style: ['retro', 'klassinen'],
    keywords: ['vati', 'astiat', 'keräily'],
  }),
  product({
    id: 'p-032',
    title: 'Iittala Kartio lasit 6 kpl',
    brand: 'Iittala',
    category: 'Astiat',
    sizeGroup: 'none',
    condition: 'Hyvä',
    price: 38,
    marketId: 'm-lanttila',
    spot: 'Hylly D2',
    addedDaysAgo: 0,
    color: 'Kirkas',
    style: ['skandi', 'minimalistinen'],
    keywords: ['lasit', 'astiat', 'juomalasi'],
  }),
  product({
    id: 'p-033',
    title: 'Arabia 24h kulhot 4 kpl',
    brand: 'Arabia',
    category: 'Astiat',
    sizeGroup: 'none',
    condition: 'Hyvä',
    price: 22,
    marketId: 'm-lanttila',
    spot: 'Pöytä 31',
    addedDaysAgo: 2,
    color: 'Valkoinen',
    style: ['minimalistinen'],
    keywords: ['kulhot', 'astiat', 'keittiö'],
  }),
  product({
    id: 'p-034',
    title: 'Marimekko Oiva mukit 2 kpl',
    brand: 'Marimekko',
    category: 'Astiat',
    sizeGroup: 'none',
    condition: 'Uudenveroinen',
    price: 24,
    marketId: 'm-lanttila',
    spot: 'Hylly D3',
    addedDaysAgo: 0,
    color: 'Valkoinen ja musta',
    style: ['skandi', 'värikäs'],
    keywords: ['muki', 'astiat', 'kahvi'],
  }),
  product({
    id: 'p-035',
    title: 'Arabia Kilta lautanen',
    brand: 'Arabia',
    category: 'Astiat',
    sizeGroup: 'none',
    condition: 'Käytetty',
    price: 18,
    marketId: 'm-lanttila',
    spot: 'Vitriini 1',
    addedDaysAgo: 5,
    color: 'Sininen',
    style: ['retro'],
    status: 'sold',
    keywords: ['lautanen', 'astiat', 'keräily'],
  }),
  product({
    id: 'p-036',
    title: 'Iittala Aalto maljakko 95 mm',
    brand: 'Iittala',
    category: 'Astiat',
    sizeGroup: 'none',
    condition: 'Hyvä',
    price: 55,
    marketId: 'm-lanttila',
    spot: 'Vitriini 2',
    addedDaysAgo: 1,
    color: 'Kirkas',
    style: ['skandi', 'klassinen'],
    keywords: ['maljakko', 'astiat', 'lasi'],
  }),
  product({
    id: 'p-037',
    title: 'Pentik kahvikupit 4 kpl',
    brand: 'Pentik',
    category: 'Astiat',
    sizeGroup: 'none',
    condition: 'Hyvä',
    price: 20,
    marketId: 'm-hyrra',
    spot: 'Pöytä 10',
    addedDaysAgo: 1,
    color: 'Ruskea',
    style: ['maanläheinen'],
    keywords: ['kahvikupit', 'astiat', 'kahvi'],
  }),
  product({
    id: 'p-038',
    title: 'Arabia Anemone kahvikuppi',
    brand: 'Arabia',
    category: 'Astiat',
    sizeGroup: 'none',
    condition: 'Hyvä',
    price: 28,
    marketId: 'm-hyrra',
    spot: 'Hylly A1',
    addedDaysAgo: 3,
    color: 'Sinivalkoinen',
    style: ['retro', 'klassinen'],
    keywords: ['kahvikuppi', 'astiat', 'keräily'],
  }),
  product({
    id: 'p-039',
    title: 'Iittala Ultima Thule lasit 4 kpl',
    brand: 'Iittala',
    category: 'Astiat',
    sizeGroup: 'none',
    condition: 'Hyvä',
    price: 42,
    marketId: 'm-lanttila',
    spot: 'Hylly D1',
    addedDaysAgo: 2,
    color: 'Kirkas',
    style: ['skandi', 'klassinen'],
    keywords: ['lasit', 'astiat', 'juomalasi'],
  }),
  product({
    id: 'p-040',
    title: 'Rörstrand Mon Amie kulho',
    brand: 'Rörstrand',
    category: 'Astiat',
    sizeGroup: 'none',
    condition: 'Hyvä',
    price: 26,
    marketId: 'm-hyrra',
    spot: 'Pöytä 12',
    addedDaysAgo: 4,
    color: 'Sinivalkoinen',
    style: ['retro'],
    keywords: ['kulho', 'astiat'],
  }),
  product({
    id: 'p-041',
    title: 'Arabia Muumi muki, Muumipeikko',
    brand: 'Arabia',
    category: 'Astiat',
    sizeGroup: 'none',
    condition: 'Uudenveroinen',
    price: 22,
    marketId: 'm-lanttila',
    spot: 'Vitriini 2',
    addedDaysAgo: 0,
    color: 'Valkoinen',
    style: ['klassinen'],
    keywords: ['muki', 'muumi', 'astiat', 'keräily'],
  }),
  product({
    id: 'p-042',
    title: 'Iittala Teema kulhot 2 kpl',
    brand: 'Iittala',
    category: 'Astiat',
    sizeGroup: 'none',
    condition: 'Hyvä',
    price: 24,
    marketId: 'm-lanttila',
    spot: 'Hylly D2',
    addedDaysAgo: 1,
    color: 'Hiekka',
    style: ['skandi', 'maanläheinen'],
    keywords: ['kulho', 'astiat', 'keittiö'],
  }),

  /* -------- Muu valikoima -------- */
  product({
    id: 'p-050',
    title: 'Marimekko Tasaraita paita',
    brand: 'Marimekko',
    category: 'Vaatteet',
    size: 'S',
    sizeGroup: 'adult',
    condition: 'Hyvä',
    price: 22,
    marketId: 'm-kanuuna',
    spot: 'Pöytä 3',
    addedDaysAgo: 0,
    color: 'Raidallinen',
    style: ['skandi', 'klassinen'],
    keywords: ['paita', 'raidat', 'trikoo'],
  }),
  product({
    id: 'p-051',
    title: 'Ruskea nahkatakki',
    category: 'Vaatteet',
    size: 'M',
    sizeGroup: 'adult',
    condition: 'Hyvä',
    price: 65,
    marketId: 'm-zirppari',
    spot: 'Puomi 6',
    addedDaysAgo: 1,
    color: 'Ruskea',
    style: ['vintage', 'maanläheinen'],
    keywords: ['nahkatakki', 'takki', 'nahka'],
  }),
  product({
    id: 'p-052',
    title: 'Villakangastakki',
    brand: 'Filippa K',
    category: 'Vaatteet',
    size: 'L',
    sizeGroup: 'adult',
    condition: 'Hyvä',
    price: 48,
    marketId: 'm-hertsika',
    spot: 'Puomi 2',
    addedDaysAgo: 2,
    color: 'Beige',
    style: ['minimalistinen', 'maanläheinen'],
    keywords: ['takki', 'villakangas', 'päällystakki'],
  }),
  product({
    id: 'p-053',
    title: 'Samettinen koristetyyny',
    category: 'Sisustus',
    sizeGroup: 'none',
    condition: 'Uudenveroinen',
    price: 12,
    marketId: 'm-ogeli',
    spot: 'Hylly B1',
    addedDaysAgo: 0,
    color: 'Okra',
    style: ['maanläheinen', 'värikäs'],
    keywords: ['tyyny', 'sisustus', 'sametti'],
  }),
  product({
    id: 'p-054',
    title: 'Rottinkituoli',
    category: 'Sisustus',
    sizeGroup: 'none',
    condition: 'Hyvä',
    price: 75,
    marketId: 'm-hiiden',
    spot: 'Alue C',
    addedDaysAgo: 2,
    color: 'Luonnonvärinen',
    style: ['vintage', 'maanläheinen'],
    keywords: ['tuoli', 'huonekalu', 'rottinki'],
  }),
  product({
    id: 'p-055',
    title: 'Iittala Kivi kynttilälyhdyt 3 kpl',
    brand: 'Iittala',
    category: 'Sisustus',
    sizeGroup: 'none',
    condition: 'Hyvä',
    price: 30,
    marketId: 'm-nurkka',
    spot: 'Hylly A4',
    addedDaysAgo: 1,
    color: 'Kirkas',
    style: ['skandi', 'minimalistinen'],
    keywords: ['kynttilä', 'lyhty', 'sisustus'],
  }),
  product({
    id: 'p-056',
    title: 'Vintage nahkalaukku',
    category: 'Vintage',
    sizeGroup: 'none',
    condition: 'Käytetty',
    price: 45,
    marketId: 'm-nurkka',
    spot: 'Pöytä 9',
    addedDaysAgo: 3,
    color: 'Konjakinruskea',
    style: ['vintage', 'maanläheinen'],
    keywords: ['laukku', 'nahka', 'vintage'],
  }),
  product({
    id: 'p-057',
    title: 'Converse Chuck Taylor tennarit',
    brand: 'Converse',
    category: 'Jalkineet',
    size: '39',
    sizeGroup: 'shoes',
    condition: 'Hyvä',
    price: 25,
    marketId: 'm-keidas',
    spot: 'Hylly B3',
    addedDaysAgo: 2,
    color: 'Musta',
    style: ['klassinen', 'retro'],
    keywords: ['tennarit', 'kengät', 'converse'],
  }),
  product({
    id: 'p-058',
    title: 'Marimekko Unikko verhot',
    brand: 'Marimekko',
    category: 'Sisustus',
    sizeGroup: 'none',
    condition: 'Hyvä',
    price: 40,
    marketId: 'm-lykky',
    spot: 'Pöytä 5',
    addedDaysAgo: 1,
    color: 'Punainen',
    style: ['retro', 'värikäs'],
    keywords: ['verhot', 'kangas', 'sisustus'],
  }),
  product({
    id: 'p-059',
    title: 'Lastenpyörä 16 tuumaa',
    brand: 'Helkama',
    category: 'Urheilu',
    sizeGroup: 'none',
    condition: 'Hyvä',
    price: 55,
    marketId: 'm-tammela',
    spot: 'Alue D',
    addedDaysAgo: 1,
    color: 'Sininen',
    style: ['klassinen'],
    keywords: ['pyörä', 'polkupyörä', 'lapsi'],
  }),
  product({
    id: 'p-060',
    title: 'Nanso villapaita',
    brand: 'Nanso',
    category: 'Vaatteet',
    size: 'M',
    sizeGroup: 'adult',
    condition: 'Hyvä',
    price: 26,
    marketId: 'm-kangas',
    spot: 'Pöytä 7',
    addedDaysAgo: 2,
    color: 'Harmaa',
    style: ['skandi', 'minimalistinen'],
    keywords: ['villapaita', 'neule', 'paita'],
  }),
  product({
    id: 'p-061',
    title: 'Emmaljunga rattaat',
    brand: 'Emmaljunga',
    category: 'Lastentarvikkeet',
    sizeGroup: 'none',
    condition: 'Hyvä',
    price: 120,
    marketId: 'm-vekara',
    spot: 'Alue A',
    addedDaysAgo: 1,
    color: 'Musta',
    style: ['minimalistinen'],
    keywords: ['rattaat', 'vaunut', 'lapsi'],
  }),
  product({
    id: 'p-062',
    title: 'Stokke Tripp Trapp syöttötuoli',
    brand: 'Stokke',
    category: 'Lastentarvikkeet',
    sizeGroup: 'none',
    condition: 'Hyvä',
    price: 95,
    marketId: 'm-dom',
    spot: 'Alue B',
    addedDaysAgo: 0,
    color: 'Luonnonpuu',
    style: ['skandi', 'minimalistinen'],
    keywords: ['syöttötuoli', 'tuoli', 'lapsi'],
  }),
  product({
    id: 'p-063',
    title: 'Retro jakkara 1960-luvulta',
    category: 'Vintage',
    sizeGroup: 'none',
    condition: 'Käytetty',
    price: 35,
    marketId: 'm-hiiden',
    spot: 'Alue C',
    addedDaysAgo: 4,
    color: 'Teak',
    style: ['retro', 'vintage'],
    keywords: ['jakkara', 'huonekalu', 'retro'],
  }),
  product({
    id: 'p-064',
    title: 'Pellavaliina',
    category: 'Sisustus',
    sizeGroup: 'none',
    condition: 'Uudenveroinen',
    price: 16,
    marketId: 'm-keidas',
    spot: 'Pöytä 22',
    addedDaysAgo: 0,
    color: 'Luonnonvalkoinen',
    style: ['maanläheinen', 'minimalistinen'],
    keywords: ['liina', 'pellava', 'sisustus'],
  }),
  product({
    id: 'p-065',
    title: 'Nike verryttelytakki',
    brand: 'Nike',
    category: 'Urheilu',
    size: 'L',
    sizeGroup: 'adult',
    condition: 'Hyvä',
    price: 22,
    marketId: 'm-lykky',
    spot: 'Pöytä 14',
    addedDaysAgo: 2,
    color: 'Musta',
    style: ['retro'],
    keywords: ['takki', 'verryttely', 'urheilu'],
  }),
  product({
    id: 'p-066',
    title: 'Reima kumisaappaat',
    brand: 'Reima',
    category: 'Jalkineet',
    size: '28',
    sizeGroup: 'shoes',
    condition: 'Hyvä',
    price: 14,
    marketId: 'm-akirppis',
    spot: 'Hylly A2',
    addedDaysAgo: 1,
    color: 'Keltainen',
    style: ['värikäs'],
    keywords: ['saappaat', 'kengät', 'lapsi'],
  }),
  product({
    id: 'p-067',
    title: 'Käsin neulotut villasukat',
    category: 'Vaatteet',
    size: '38 ja 39',
    sizeGroup: 'adult',
    condition: 'Uudenveroinen',
    price: 15,
    marketId: 'm-akirppis',
    spot: 'Pöytä 11',
    addedDaysAgo: 0,
    color: 'Harmaa ja punainen',
    style: ['maanläheinen'],
    keywords: ['villasukat', 'sukat', 'käsityö'],
  }),
  product({
    id: 'p-068',
    title: 'Finlayson päiväpeite',
    brand: 'Finlayson',
    category: 'Sisustus',
    sizeGroup: 'none',
    condition: 'Hyvä',
    price: 28,
    marketId: 'm-oulu-iso',
    spot: 'Hylly E1',
    addedDaysAgo: 2,
    color: 'Sininen',
    style: ['retro', 'värikäs'],
    keywords: ['peite', 'päiväpeite', 'sisustus'],
  }),
  product({
    id: 'p-069',
    title: 'Marimekko Jokapoika paita',
    brand: 'Marimekko',
    category: 'Vaatteet',
    size: 'M',
    sizeGroup: 'adult',
    condition: 'Hyvä',
    price: 35,
    marketId: 'm-tammela',
    spot: 'Pöytä 3',
    addedDaysAgo: 0,
    color: 'Sinivalkoinen',
    style: ['skandi', 'klassinen'],
    keywords: ['paita', 'kauluspaita', 'raidat'],
  }),
  product({
    id: 'p-070',
    title: 'Tove Jansson: Muumilaakson marraskuu',
    category: 'Kirjat',
    sizeGroup: 'none',
    condition: 'Hyvä',
    price: 8,
    marketId: 'm-kangas',
    spot: 'Hylly K2',
    addedDaysAgo: 1,
    color: 'Sininen',
    style: ['klassinen'],
    keywords: ['kirja', 'muumi', 'romaani'],
  }),
  product({
    id: 'p-071',
    title: 'Vinyylilevy, suomirock 1978',
    category: 'Vintage',
    sizeGroup: 'none',
    condition: 'Käytetty',
    price: 12,
    marketId: 'm-kangas',
    spot: 'Pöytä 19',
    addedDaysAgo: 3,
    color: 'Musta',
    style: ['retro', 'vintage'],
    keywords: ['vinyyli', 'levy', 'musiikki'],
  }),
  product({
    id: 'p-072',
    title: 'Villakangastakki lapselle',
    brand: 'Mini Rodini',
    category: 'Lastentarvikkeet',
    size: '122',
    sizeGroup: 'kids',
    condition: 'Uudenveroinen',
    price: 32,
    marketId: 'm-hertsika',
    spot: 'Pöytä 21',
    addedDaysAgo: 0,
    color: 'Ruskea',
    style: ['skandi', 'maanläheinen'],
    keywords: ['takki', 'villakangas', 'lapsi'],
  }),
  product({
    id: 'p-073',
    title: 'Iittala Teema mukit 4 kpl',
    brand: 'Iittala',
    category: 'Astiat',
    sizeGroup: 'none',
    condition: 'Hyvä',
    price: 32,
    marketId: 'm-hyrra',
    spot: 'Hylly A1',
    addedDaysAgo: 0,
    color: 'Valkoinen',
    style: ['skandi', 'minimalistinen'],
    keywords: ['muki', 'astiat', 'kahvi'],
  }),
  product({
    id: 'p-074',
    title: 'Lasten juhlamekko, pitsikaulus',
    brand: 'Newbie',
    category: 'Lastentarvikkeet',
    size: '110',
    sizeGroup: 'kids',
    condition: 'Hyvä',
    price: 16,
    marketId: 'm-koto',
    spot: 'Hylly C1',
    addedDaysAgo: 0,
    color: 'Vaaleanbeige',
    style: ['klassinen', 'maanläheinen'],
    keywords: ['mekko', 'juhlamekko', 'lapsi'],
  }),
];

/* ---------------------------------------------------------------------------
   Lookups and derived helpers
--------------------------------------------------------------------------- */

export const marketById = (id: string): Market | undefined => markets.find((m) => m.id === id);

export const productById = (id: string): Product | undefined => products.find((p) => p.id === id);

export const productsByMarket = (marketId: string): Product[] =>
  products.filter((p) => p.marketId === marketId);

export const cities: string[] = Array.from(new Set(markets.map((m) => m.city))).sort((a, b) =>
  a.localeCompare(b, 'fi'),
);

export const categories: Category[] = [
  'Vaatteet',
  'Lastentarvikkeet',
  'Astiat',
  'Sisustus',
  'Vintage',
  'Jalkineet',
  'Urheilu',
  'Kirjat',
];

export const conditions: Condition[] = ['Uudenveroinen', 'Hyvä', 'Käytetty'];

export const kidsSizes = ['80', '86', '92', '98', '104', '110', '116', '122', '128', '134', '140'];
export const adultSizes = ['XS', 'S', 'M', 'L', 'XL'];
export const shoeSizes = ['24', '26', '28', '30', '36', '38', '39', '40', '42'];

export const trendingSearches = [
  "Levi's",
  'Marimekko',
  'Lastenvaatteet',
  'Iittala',
  'Nahkatakki',
  'Haalari 122',
];

/** Products added today, used by the "Uutta tänään" rows. */
export const newToday = (marketId?: string): Product[] =>
  products.filter(
    (p) => p.addedDaysAgo === 0 && p.status !== 'sold' && (!marketId || p.marketId === marketId),
  );

export function addedLabel(daysAgo: number): string {
  if (daysAgo === 0) return 'Tänään';
  if (daysAgo === 1) return 'Eilen';
  return `${daysAgo} päivää sitten`;
}

export function formatPrice(price: number): string {
  return `${price.toFixed(2).replace('.', ',')} €`;
}

/** Simple market level counter used when ranking markets by assortment. */
export function categoryCount(marketId: string, category: Category): number {
  return products.filter(
    (p) => p.marketId === marketId && p.category === category && p.status !== 'sold',
  ).length;
}
